---
title: "Ganciclovir"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(truncnorm)
library(mrgsolve)

library(mrgsolve)
library(mapbayr)

library(dplyr)

library(magrittr)
library(ggplot2)
library(PKNCA)
library(ggplot2)
library(ggcorrplot)
library(blandr)
library(DALEX)
library(tidymodels)

```

simulation Age/poids/clairance 

```{r}
### on va simuler poids/creat en fonction les classes d'âgeet du sex  
### pour le poids , on prend les données de l'OMS 
### pour la créat , 

####on va commencer par les filles 


### poids 0/1 ans 
set.seed(2345)
gen_1 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=8.3, b=13.3, mean = 10.93, sd = 3))}
W_1 <- 1:1 %>% map_df(gen_1)%>% dplyr::mutate(age=1) 

### on ajoute variation de taille 0/1 ans  
set.seed(2345)
taille_1 <-  function (x) {tibble(ID1 = x, taille= rtruncnorm(300, a=68, b=95, mean = 83, sd = 3))}
T_1 <- 1:1 %>% map_df(taille_1)

W_1 <- W_1 %>% bind_cols(T_1) %>% select(Pds,taille,age)
summary(W_1)


set.seed(2345)
gen_2 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=10, b=18, mean =13.3, sd = 3.5))}
W_2 <- 1:1 %>% map_df(gen_2) %>% mutate(age=2)

####  onajoute la taille 
set.seed(2345)
taille_2 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=82, b=100, mean = 90, sd = 3))}
T_2 <- 1:1 %>% map_df(taille_2)

W_2 <- W_2 %>% bind_cols(T_2) %>% select(Pds,taille,age)
summary(W_2)


### on associe les 2 
Simu_inf2 <- W_1 %>% bind_rows(W_2) 
summary(Simu_inf2)

### pour la cl creat on prend article de Benedicte  150 [56–345]

set.seed(2345)
gen_Clcreat <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(600, a=10, b=340, mean =90, sd = 250))}
Clcreat<- 1:1 %>% map_df(gen_Clcreat)

Simu_inf2 <- Simu_inf2 %>% bind_cols(Clcreat)
Simu_inf2 <- as.tibble(Simu_inf2 )%>% select(Pds,Clcreat,age,taille)%>% mutate(ID = 1:600)

### on associe 3, 4, 5 

set.seed(2345)
gen_3 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=12, b=20, mean =14.3, sd = 3.5))}
W_3 <- 1:1 %>% map_df(gen_3) %>% mutate(age=3)

### on ajoute taille 3 ans 
set.seed(2345)
taille_3 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=88, b=110, mean = 98, sd = 3))}
T_3 <- 1:1 %>% map_df(taille_3)

W_3 <- W_3 %>% bind_cols(T_3) %>% select(Pds,taille,age)


set.seed(2345)
gen_4 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=12.4, b=23.3, mean =15.3, sd = 3.5))}
W_4<- 1:1 %>% map_df(gen_4) %>% mutate(age=4)

### on ajoute taille 4 ans  
set.seed(2345)
taille_4 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=93, b=120, mean = 118, sd = 3.5))}
T_4 <- 1:1 %>% map_df(taille_4)

W_4 <- W_4 %>% bind_cols(T_4)%>% select(Pds,taille,age)


set.seed(2345)
gen_5 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=14.2, b=29.7, mean =19.5, sd = 3.5))}
W_5<- 1:1 %>% map_df(gen_5) %>% mutate(age=5)

set.seed(2345)
taille_5 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=100, b=129, mean = 112, sd = 3.5))}
T_5 <- 1:1 %>% map_df(taille_5)

W_5 <- W_5 %>% bind_cols(T_5)%>% select(Pds,taille,age)


Simu3_5 <- W_3 %>% bind_rows( W_4) %>% bind_rows( W_5)
set.seed(2345)
gen_Clcreat3_5 <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(900, a=10, b=340, mean =90, sd = 250))}
Clcreat3_5<- 1:1 %>% map_df(gen_Clcreat3_5)


Simu3_5 <- Simu3_5 %>% bind_cols(Clcreat3_5)
Simu3_5 <- as.tibble(Simu3_5) %>% select(Pds,Clcreat,age,taille)%>% mutate (ID=601:1500)

### on associe 6/7/8/9/10/11


set.seed(2345)
gen_6 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=16, b=32, mean =22, sd = 3.5))}
W_6<- 1:1 %>% map_df(gen_6) %>% mutate(age=6)

set.seed(2345)
taille_6 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=104, b=134, mean = 124, sd = 3.5))}
T_6 <- 1:1 %>% map_df(taille_6)

W_6 <- W_6 %>% bind_cols(T_6)%>% select(Pds,taille,age)



set.seed(2345)
gen_7 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=18, b=38.3, mean =24, sd = 5.5))}
W_7<- 1:1 %>% map_df(gen_7) %>% mutate(age=7)
set.seed(2345)
taille_7 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=108, b=143, mean = 124, sd = 5.5))}
T_7 <- 1:1 %>% map_df(taille_7)

W_7 <- W_7 %>% bind_cols(T_7)%>% select(Pds,taille,age)


set.seed(2345)
gen_8 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=19, b=44, mean =28.2, sd = 6.5))}
W_8<- 1:1 %>% map_df(gen_8) %>% mutate(age=8)
set.seed(2345)
taille_8 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=108, b=152, mean = 137.7, sd = 6.5))}
T_8 <- 1:1 %>% map_df(taille_8)

W_8 <- W_8 %>% bind_cols(T_8)%>% select(Pds,taille,age)


set.seed(2345)
gen_9 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=21, b=49.5, mean =29.5, sd = 7.5))}
W_9<- 1:1 %>% map_df(gen_9) %>% mutate(age=9)
set.seed(2345)
taille_9 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=118, b=154, mean = 135, sd = 7.5))}
T_9 <- 1:1 %>% map_df(taille_9)

W_9 <- W_9 %>% bind_cols(T_9)%>% select(Pds,taille,age)


set.seed(2345)
gen_10 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=22, b=52, mean =323.5, sd = 7.5))}
W_10<- 1:1 %>% map_df(gen_10)  %>% mutate(age=10)
set.seed(2345)
taille_10 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=122, b=165, mean = 141, sd = 7.5))}
T_10 <- 1:1 %>% map_df(taille_10)

W_10 <- W_10 %>% bind_cols(T_10)%>% select(Pds,taille,age)



set.seed(2345)
gen_11 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=24.5, b=64.5, mean =40, sd = 7.5))}
W_11<- 1:1 %>% map_df(gen_11)  %>% mutate(age=11)

set.seed(2345)
taille_11 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=124, b=175, mean = 148, sd = 7.5))}
T_11 <- 1:1 %>% map_df(taille_11)

W_11 <- W_11 %>% bind_cols(T_11)%>% select(Pds,taille,age)


Simu6_11 <- W_6 %>% bind_rows(W_7)%>% bind_rows(W_8)%>% bind_rows(W_9)%>% bind_rows(W_10)%>% bind_rows(W_11)
set.seed(2345)
gen_Clcreat6_11 <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(1800, a=10, b=340, mean =90, sd = 250))}
Clcreat6_11<- 1:1 %>% map_df(gen_Clcreat6_11)


Simu6_11 <- Simu6_11 %>% bind_cols(Clcreat6_11)
Simu6_11 <- as.tibble(Simu6_11) %>% select(Pds,Clcreat,age,taille)%>% mutate (ID=1501:3300)
summary(Simu6_11)

### on associe les autres ages 

set.seed(2345)
gen_12 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=28, b=75, mean =46.5, sd = 8.5))}
W_12<- 1:1 %>% map_df(gen_12) %>% mutate(age=12)
set.seed(2345)
taille_12 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=125, b=182, mean = 155, sd = 8.5))}
T_12 <- 1:1 %>% map_df(taille_12)

W_12 <- W_12 %>% bind_cols(T_12)%>% select(Pds,taille,age)



set.seed(2345)
gen_13 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=28, b=80, mean =48, sd = 9.5))}
W_13<- 1:1 %>% map_df(gen_13) %>% mutate(age=13)
set.seed(2345)
taille_13 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=132, b=180, mean = 152, sd = 9.5))}
T_13 <- 1:1 %>% map_df(taille_13)

W_13 <- W_13 %>% bind_cols(T_13)%>% select(Pds,taille,age)


set.seed(2345)
gen_14 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=33, b=86, mean =50, sd = 10.5))}
W_14<- 1:1 %>% map_df(gen_14) %>% mutate(age=14)
set.seed(2345)
taille_14 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=140, b=190, mean = 165, sd = 10.5))}
T_14 <- 1:1 %>% map_df(taille_14)

W_14 <- W_14 %>% bind_cols(T_14)%>% select(Pds,taille,age)


set.seed(2345)
gen_15 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=36, b=92, mean =55, sd = 10.5))}
W_15<- 1:1 %>% map_df(gen_15) %>% mutate(age=15)
set.seed(2345)
taille_15 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=144, b=195, mean = 165, sd = 10.5))}
T_15 <- 1:1 %>% map_df(taille_15)

W_15 <- W_15 %>% bind_cols(T_15)%>% select(Pds,taille,age)


set.seed(2345)
gen_16 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=40, b=95, mean =57, sd = 10.5))}
W_16<- 1:1 %>% map_df(gen_16) %>% mutate(age=16)
set.seed(2345)
taille_16 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=144, b=195, mean = 165, sd = 10.5))}
T_16 <- 1:1 %>% map_df(taille_16)

W_16 <- W_16 %>% bind_cols(T_16)%>% select(Pds,taille,age)



set.seed(2345)
gen_17 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=43, b=99, mean =59, sd = 10.5))}
W_17<- 1:1 %>% map_df(gen_17) %>% mutate(age=17)
set.seed(2345)
taille_17 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=144, b=195, mean = 165, sd = 10.5))}
T_17 <- 1:1 %>% map_df(taille_17)

W_17 <- W_17 %>% bind_cols(T_17)%>% select(Pds,taille,age)



set.seed(2345)
gen_18 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=43, b=99, mean =59, sd = 10.5))}
W_18<- 1:1 %>% map_df(gen_18) %>% mutate(age=18)
set.seed(2345)
taille_18 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=144, b=195, mean = 165, sd = 10.5))}
T_18 <- 1:1 %>% map_df(taille_18)

W_18 <- W_18 %>% bind_cols(T_18)%>% select(Pds,taille,age)




simu12_18 <- W_12 %>% bind_rows(W_13) %>% bind_rows(W_14) %>% bind_rows(W_15) %>% bind_rows(W_16) %>% bind_rows(W_17) %>% bind_rows(W_18)
set.seed(2345)
gen_Clcreat12_18 <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(2100, a=10, b=340, mean =90, sd = 250))}
Clcreat12_18<- 1:1 %>% map_df(gen_Clcreat12_18)


simu12_18 <- simu12_18 %>% bind_cols(Clcreat12_18)
Simu12_18 <- as.tibble(simu12_18) %>% select(Pds,Clcreat,age,taille)%>% mutate (ID=3301:5400)

summary(Simu12_18)


Simu_totale_fille <- Simu_inf2 %>% bind_rows(Simu3_5)%>% bind_rows(Simu6_11)%>% bind_rows(simu12_18) %>% select(Pds,Clcreat,age,taille)%>% mutate(ID=c(1:5400))%>% mutate(SEX="fille")
summary(Simu_totale_fille)


### on fait ça pour les boys 


### poids 0/1 ans 
set.seed(2345)
gen_1 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=7.3, b=16.3, mean = 11.93, sd = 3))}
W_1 <- 1:1 %>% map_df(gen_1)%>% dplyr::mutate(age=1) 

### on ajoute variation de taille 0/1 ans  
set.seed(2345)
taille_1 <-  function (x) {tibble(ID1 = x, taille= rtruncnorm(300, a=72, b=95, mean = 83, sd = 3))}
T_1 <- 1:1 %>% map_df(taille_1)

W_1 <- W_1 %>% bind_cols(T_1) %>% select(Pds,taille,age)
summary(W_1)


set.seed(2345)
gen_2 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=9.5, b=20, mean =13.8, sd = 3.5))}
W_2 <- 1:1 %>% map_df(gen_2) %>% mutate(age=2)

####  onajoute la taille 
set.seed(2345)
taille_2 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=79, b=108, mean = 92, sd = 3))}
T_2 <- 1:1 %>% map_df(taille_2)

W_2 <- W_2 %>% bind_cols(T_2) %>% select(Pds,taille,age)
summary(W_2)


### on associe les 2 
Simu_inf2 <- W_1 %>% bind_rows(W_2) 
summary(Simu_inf2)

### pour la cl creat on prend article de Benedicte  150 [56–345]

set.seed(2345)
gen_Clcreat <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(600, a=10, b=340, mean =90, sd = 250))}
Clcreat<- 1:1 %>% map_df(gen_Clcreat)

Simu_inf2 <- Simu_inf2 %>% bind_cols(Clcreat)
Simu_inf2 <- as.tibble(Simu_inf2 )%>% select(Pds,Clcreat,age,taille)%>% mutate(ID = 1:600)

### on associe 3, 4, 5 

set.seed(2345)
gen_3 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=11, b=22, mean =15.3, sd = 3.5))}
W_3 <- 1:1 %>% map_df(gen_3) %>% mutate(age=3)

### on ajoute taille 3 ans 
set.seed(2345)
taille_3 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=86, b=118, mean = 100, sd = 3))}
T_3 <- 1:1 %>% map_df(taille_3)

W_3 <- W_3 %>% bind_cols(T_3) %>% select(Pds,taille,age)


set.seed(2345)
gen_4 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=12.4, b=25.3, mean =17.3, sd = 3.5))}
W_4<- 1:1 %>% map_df(gen_4) %>% mutate(age=4)

### on ajoute taille 4 ans  
set.seed(2345)
taille_4 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=92, b=124, mean = 108, sd = 3.5))}
T_4 <- 1:1 %>% map_df(taille_4)

W_4 <- W_4 %>% bind_cols(T_4)%>% select(Pds,taille,age)


set.seed(2345)
gen_5 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=15, b=30, mean =19.8, sd = 3.5))}
W_5<- 1:1 %>% map_df(gen_5) %>% mutate(age=5)

set.seed(2345)
taille_5 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=98, b=137, mean = 115, sd = 3.5))}
T_5 <- 1:1 %>% map_df(taille_5)

W_5 <- W_5 %>% bind_cols(T_5)%>% select(Pds,taille,age)


Simu3_5 <- W_3 %>% bind_rows( W_4) %>% bind_rows( W_5)
set.seed(2345)
gen_Clcreat3_5 <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(900, a=10, b=340, mean =90, sd = 250))}
Clcreat3_5<- 1:1 %>% map_df(gen_Clcreat3_5)


Simu3_5 <- Simu3_5 %>% bind_cols(Clcreat3_5)
Simu3_5 <- as.tibble(Simu3_5) %>% select(Pds,Clcreat,age,taille)%>% mutate (ID=601:1500)

### on associe 6/7/8/9/10/11


set.seed(2345)
gen_6 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=15, b=30, mean =22, sd = 3.5))}
W_6<- 1:1 %>% map_df(gen_6) %>% mutate(age=6)

set.seed(2345)
taille_6 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=102, b=140, mean = 122, sd = 3.5))}
T_6 <- 1:1 %>% map_df(taille_6)

W_6 <- W_6 %>% bind_cols(T_6)%>% select(Pds,taille,age)



set.seed(2345)
gen_7 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=17, b=35.3, mean =25, sd = 5.5))}
W_7<- 1:1 %>% map_df(gen_7) %>% mutate(age=7)
set.seed(2345)
taille_7 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=108, b=145, mean = 125, sd = 5.5))}
T_7 <- 1:1 %>% map_df(taille_7)

W_7 <- W_7 %>% bind_cols(T_7)%>% select(Pds,taille,age)


set.seed(2345)
gen_8 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=19, b=48, mean =28, sd = 6.5))}
W_8<- 1:1 %>% map_df(gen_8) %>% mutate(age=8)
set.seed(2345)
taille_8 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=112, b=152, mean = 132, sd = 6.5))}
T_8 <- 1:1 %>% map_df(taille_8)

W_8 <- W_8 %>% bind_cols(T_8)%>% select(Pds,taille,age)



set.seed(2345)
gen_9 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=21, b=49.5, mean =29.5, sd = 7.5))}
W_9<- 1:1 %>% map_df(gen_9) %>% mutate(age=9)
set.seed(2345)
taille_9 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=116, b=160, mean = 138, sd = 7.5))}
T_9 <- 1:1 %>% map_df(taille_9)

W_9 <- W_9 %>% bind_cols(T_9)%>% select(Pds,taille,age)


set.seed(2345)
gen_10 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=23, b=62, mean =33.5, sd = 7.5))}
W_10<- 1:1 %>% map_df(gen_10)  %>% mutate(age=10)
set.seed(2345)
taille_10 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=120, b=165, mean = 142, sd = 7.5))}
T_10 <- 1:1 %>% map_df(taille_10)

W_10 <- W_10 %>% bind_cols(T_10)%>% select(Pds,taille,age)



set.seed(2345)
gen_11 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=24.5, b=69.5, mean =38, sd = 7.5))}
W_11<- 1:1 %>% map_df(gen_11)  %>% mutate(age=11)

set.seed(2345)
taille_11 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=125, b=173, mean = 148, sd = 7.5))}
T_11 <- 1:1 %>% map_df(taille_11)

W_11 <- W_11 %>% bind_cols(T_11)%>% select(Pds,taille,age)


Simu6_11 <- W_6 %>% bind_rows(W_7)%>% bind_rows(W_8)%>% bind_rows(W_9)%>% bind_rows(W_10)%>% bind_rows(W_11)
set.seed(2345)
gen_Clcreat6_11 <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(1800, a=10, b=340, mean =90, sd = 250))}
Clcreat6_11<- 1:1 %>% map_df(gen_Clcreat6_11)


Simu6_11 <- Simu6_11 %>% bind_cols(Clcreat6_11)
Simu6_11 <- as.tibble(Simu6_11) %>% select(Pds,Clcreat,age,taille)%>% mutate (ID=1501:3300)
summary(Simu6_11)

### on associe les autres ages 

set.seed(2345)
gen_12 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=26, b=80, mean =42, sd = 8.5))}
W_12<- 1:1 %>% map_df(gen_12) %>% mutate(age=12)
set.seed(2345)
taille_12 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=128, b=182, mean = 155, sd = 8.5))}
T_12 <- 1:1 %>% map_df(taille_12)

W_12 <- W_12 %>% bind_cols(T_12)%>% select(Pds,taille,age)



set.seed(2345)
gen_13 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=28, b=80, mean =48, sd = 9.5))}
W_13<- 1:1 %>% map_df(gen_13) %>% mutate(age=13)
set.seed(2345)
taille_13 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=132, b=190, mean = 161, sd = 9.5))}
T_13 <- 1:1 %>% map_df(taille_13)

W_13 <- W_13 %>% bind_cols(T_13)%>% select(Pds,taille,age)


set.seed(2345)
gen_14 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=33, b=92, mean =55, sd = 10.5))}
W_14<- 1:1 %>% map_df(gen_14) %>% mutate(age=14)
set.seed(2345)
taille_14 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=136, b=195, mean = 177, sd = 10.5))}
T_14 <- 1:1 %>% map_df(taille_14)

W_14 <- W_14 %>% bind_cols(T_14)%>% select(Pds,taille,age)


set.seed(2345)
gen_15 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=36, b=92, mean =60, sd = 10.5))}
W_15<- 1:1 %>% map_df(gen_15) %>% mutate(age=15)
set.seed(2345)
taille_15 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=144, b=195, mean = 172, sd = 10.5))}
T_15 <- 1:1 %>% map_df(taille_15)

W_15 <- W_15 %>% bind_cols(T_15)%>% select(Pds,taille,age)


set.seed(2345)
gen_16 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=40, b=95, mean =62, sd = 10.5))}
W_16<- 1:1 %>% map_df(gen_16) %>% mutate(age=16)
set.seed(2345)
taille_16 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=144, b=195, mean = 175, sd = 10.5))}
T_16 <- 1:1 %>% map_df(taille_16)

W_16 <- W_16 %>% bind_cols(T_16)%>% select(Pds,taille,age)



set.seed(2345)
gen_17 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=43, b=110, mean =65, sd = 10.5))}
W_17<- 1:1 %>% map_df(gen_17) %>% mutate(age=17)
set.seed(2345)
taille_17 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=154, b=195, mean = 175, sd = 10.5))}
T_17 <- 1:1 %>% map_df(taille_17)

W_17 <- W_17 %>% bind_cols(T_17)%>% select(Pds,taille,age)



set.seed(2345)
gen_18 <-  function (x) {tibble(ID1 = x, Pds= rtruncnorm(300, a=43, b=99, mean =65, sd = 10.5))}
W_18<- 1:1 %>% map_df(gen_18) %>% mutate(age=18)
set.seed(2345)
taille_18 <-  function (x) {tibble(ID1 = x, taille = rtruncnorm(300, a=144, b=195, mean = 175, sd = 10.5))}
T_18 <- 1:1 %>% map_df(taille_18)

W_18 <- W_18 %>% bind_cols(T_18)%>% select(Pds,taille,age)




simu12_18 <- W_12 %>% bind_rows(W_13) %>% bind_rows(W_14) %>% bind_rows(W_15) %>% bind_rows(W_16) %>% bind_rows(W_17) %>% bind_rows(W_18)
set.seed(2345)
gen_Clcreat12_18 <-  function (x) {tibble(ID1 = x, Clcreat= rtruncnorm(2100, a=10, b=340, mean =90, sd = 250))}
Clcreat12_18<- 1:1 %>% map_df(gen_Clcreat12_18)


simu12_18 <- simu12_18 %>% bind_cols(Clcreat12_18)
Simu12_18 <- as.tibble(simu12_18) %>% select(Pds,Clcreat,age,taille)%>% mutate (ID=3301:5400)

summary(Simu12_18)






Simu_totale_boy<- Simu_inf2 %>% bind_rows(Simu3_5)%>% bind_rows(Simu6_11)%>% bind_rows(simu12_18) %>% select(Pds,Clcreat,age,taille)%>% mutate(ID=c(1:5400))%>% mutate(SEX="garcon")
summary(Simu_totale_boy)


Simu_totale <- Simu_totale_boy %>% bind_rows(Simu_totale_fille) %>% select(-ID)%>% mutate(ID=c(1:10800))


Simu_totale <- Simu_totale %>% mutate(SC_mosteller= sqrt((taille*Pds)/3600))
summary(Simu_totale)



Simu_totale<- Simu_totale %>% mutate(type_greffe= sample(1:2,10800,replace=T))
Simu_totale$type_greffe=as.factor(Simu_totale$type_greffe)


Simu_totale<- Simu_totale %>% mutate(greffe= case_when(type_greffe=="1"~"solide",type_greffe=="2"~"moelle" ))%>% select(-type_greffe)


Simu_totale_avec_dose2 <- Simu_totale %>% mutate (Clcreat2 = case_when(Clcreat<150 ~ Clcreat, Clcreat>=150 ~ 150))%>%mutate(amt= 7*SC_mosteller*Clcreat2)%>% mutate(amt2 = case_when(amt<900 ~ amt, amt>=900 ~ 900))


set.seed(123)  
sample <- sample.int(n = nrow(Simu_totale_avec_dose2), size = floor(.25*nrow(Simu_totale_avec_dose2)), replace = F)

data_bene <- Simu_totale_avec_dose2[sample, ]
Simu_totale_avec_dose2_2  <- Simu_totale_avec_dose2[-sample, ]


set.seed(123)  
sample2 <- sample.int(n = nrow(Simu_totale_avec_dose2_2), size = floor(.33*nrow(Simu_totale_avec_dose2_2)), replace = F)

data_nguyen <- Simu_totale_avec_dose2_2[sample2, ]
Simu_totale_avec_dose2_3  <- Simu_totale_avec_dose2_2[-sample2, ]


set.seed(123)  
sample3 <- sample.int(n = nrow(Simu_totale_avec_dose2_3), size = floor(.50*nrow(Simu_totale_avec_dose2_3)), replace = F)

data_pescovitz <- Simu_totale_avec_dose2_3[sample3, ]
Simu_totale_avec_dose2_4  <- Simu_totale_avec_dose2_3[-sample3, ]


set.seed(123)  
sample4 <- sample.int(n = nrow(Simu_totale_avec_dose2_4), size = floor(1*nrow(Simu_totale_avec_dose2_4)), replace = F)

data_Facchin <- Simu_totale_avec_dose2_4[sample4, ]
Simu_totale_avec_dose2_5  <- Simu_totale_avec_dose2_4[-sample4, ]








```
Franck et al 

```{r}
code_bene <- "

[PROB] #modèle Ganciclovir bjcp Franck et al 2020

[SET] end=100, delta=0.1

[PARAM] @annotated


TVKa: 0.73 : typical Ka (/h)
TVF:  0.43: Typical bioavailability (%)
TV1: 9.7 :  typical V1
TV2: 7.6:  typical  V2
TVQ : 10.9 : typical intercompartmental clearance
TVCL : 6.9 : typical CL 
WT :26.7 : median current weight 
CLCREA :148.8: median Cl creat 
CrCL: 0.88 : effet of CrCL on CL


[CMT] @annotated
DEPOT  : Dosing compartment (mg)
CENT : Central compartment
PERI : First peripheral compartment 
 

 [OMEGA] @annotated
ETACL : 0.19 : ETA on clearance
ETAV1 : 0.348 : ETA on V1
ETAKa : 0.49 : ETA on Ka
ETAF : 0.096 : ETA on F 

[MAIN]

double Ka = TVKa*exp(ETAKa);
double CL = TVCL*pow(WT/26.7,0.75)*pow(CLCREA/148.8,CrCL)*exp(ETACL);
double Q = TVQ ;
double V1 = (TV1*WT/26.5)*exp(ETAV1) ;
double V2 = TV2*WT/26.5 ;
F_DEPOT= TVF*exp(ETAF);
ALAG_DEPOT = 0.33;



[SIGMA] @annotated
ADD : 0.01 : additive Residual unexplained variability 0.98


[ODE]
dxdt_DEPOT = -Ka*DEPOT;
dxdt_CENT = Ka*DEPOT -(CL+Q)*CENT/V1 + Q*PERI/V2 ;
dxdt_PERI = Q*CENT/V1 - Q*PERI/V2 ;

[TABLE] 
capture CP = (CENT/V1)+ADD;
int i = 0;
while(CP<0 && i <100) {
simeps(1);
CP = (CENT/V1) + EPS(1);
++i;
}

"


my_model_bene <- mcode("ganciclovir_model", code_bene)


my_model_bene %>% 
  ev(am = 520 ,ss=1, ii=12) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()

my_model_bene %>% 
  ev(am = 520 ,ss=1, ii=12) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()


data <- expand.ev(ID = 1:10, amt = 520,ii=24, ss=1)#) #2,2.5,3, 3.5, 4
set.seed(2345)
sim_bene <- my_model_bene %>% 
  data_set(data) %>%
  Req(CP) %>%
 mrgsim(delta = 1, end = 24)#%>% 
  #f#ilter(time==24)
  #plot()
  #filter(time==23.9)




```
Pescovitz et al

```{r}
code_pescovitz <- "

[PROB] #modèle GanciclovirTransplant Infectious Disease Pescovitz et al 2009

[SET] end=100, delta=0.1

[PARAM] @annotated


TVKa: 0.42 : typical Ka (/h)
TVF:  0.55: Typical bioavailability (%)
TV1: 20 :  typical V1
TV2: 15:  typical  V2
TVQ : 8 : typical intercompartmental clearance
TVCL : 5.4 : etypical CL 
TVALAG:0.22: typical lag time
WT :26.7 : median current weight 
CLCREA :148.8: median Cl creat 


[CMT] @annotated
DEPOT  : Dosing compartment (mg)
CENT : Central compartment
PERI : First peripheral compartment 
 

 [OMEGA] @annotated
ETACL : 0.0029 : ETA on clearance
ETAlag: 0.001936:ETA on lagtime
ETAV1 : 0.0036 : ETA on V1
ETAV2 : 0.0045 : ETA on V2
ETAKa : 0.0256 : ETA on Ka
ETAQ: 0.0361: ETA on Q
ETAF : 0.0047 : ETA on F 

[MAIN]

double Ka = TVKa*exp(ETAKa);
double CL = TVCL*exp(ETACL);
double Q = TVQ*exp(ETAQ) ;
double V1 = TV1*exp(ETAV1) ;
double V2 = TV2*exp(ETAV1)  ;
F_DEPOT= TVF*exp(ETAF);
ALAG_DEPOT= TVALAG*exp(ETAlag);
 

[SIGMA] @annotated
PROP: 0.001: proportionnel error 0.29
ADD : 0.001 : additive Residual unexplained variability 0.14

[ODE]
dxdt_DEPOT = -Ka*DEPOT;
dxdt_CENT = Ka*DEPOT -(CL+Q)*CENT/V1 + Q*PERI/V2 ;
dxdt_PERI = Q*CENT/V1 - Q*PERI/V2 ;

[TABLE] 

capture CP = (CENT/V1)*(1+ EPS(1)) + EPS(2) ;
int i = 0;
while(CP<0 && i <100) {
simeps();
CP = (CENT/V1)*(1+ EPS(1)) + EPS(2) ;
++i;
}

"


my_model_pescovitz <- mcode("ganciclovir_model_pescovitz", code_pescovitz)


my_model_pescovitz %>% 
  ev(am = 600 ,ss=1, ii=24) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()

my_model_pescovitz %>% 
  ev(am = 520 ,ss=1, ii=24) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()


data <- expand.ev(ID = 1:10, amt = 520,ii=24, ss=1)#) #2,2.5,3, 3.5, 4
set.seed(2345)
sim_pescovitz <- my_model_pescovitz %>% 
  data_set(data) %>%
  Req(CP) %>%
 mrgsim(delta = 1, end = 24)#%>% 
  #filter(time==24)
  #plot()
  #filter(time==23.9)




```
NGuyen 

```{r}
code_nguyen <- "

[PROB] #modèle Ganciclovir  Nguyen et al 2021

[SET] end=100, delta=0.1

[PARAM] @annotated


TVKa: 0.506 : typical Ka (/h)
TVF:  0.438: Typical bioavailability (%)
TV1: 5.96 :  typical V1
TV2: 1.29:  typical  V2
TVQ : 0.222 : typical intercompartmental clearance
TVCL : 2.55 : etypical CL 
CRCL : 0.763 : effect ClCr deviation on CL 
WT :26.7 : median current weight 
CLCREA :148.8: median Cl creat 


[CMT] @annotated
DEPOT  : Dosing compartment (mg)
CENT : Central compartment
PERI : First peripheral compartment 
 

[OMEGA] @annotated
ETACL : 0.0556 : ETA on clearance
ETAV1 : 0.0484 : ETA on V1



[MAIN]
 

double Ka = TVKa;
double CL = TVCL*pow(WT/11.7,0.75)*pow(CLCREA/167,CRCL)*exp(ETACL);
double Q = TVQ*pow(WT/11.7,0.75) ;
double V1 = TV1*pow(WT/11.7,1)*exp(ETAV1);
double V2 = TV2*pow(WT/11.7,1) ;
F_DEPOT= TVF;




[SIGMA] @annotated
PROP: 0.001: proportionnel error 0.477

[ODE]
dxdt_DEPOT = -Ka*DEPOT;
dxdt_CENT = Ka*DEPOT -(CL+Q)*CENT/V1 + Q*PERI/V2 ;
dxdt_PERI = Q*CENT/V1 - Q*PERI/V2 ;

[TABLE] 
capture CP = (CENT/V1)* (1+ EPS(1));
int i = 0;
while(CP<0 && i <100) {
simeps();
CP = (CENT/V1)* (1+ EPS(1)) ;
++i;
}

"


my_model_nguyen <- mcode("ganciclovir_model_nguyen", code_nguyen)


my_model_nguyen %>% 
  ev(am = 520 ,ss=1, ii=24) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()

my_model_nguyen %>% 
  ev(am = 520 ,ss=1, ii=24) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()


data <- expand.ev(ID = 1:10, amt = 520,ii=12, ss=1)#) #2,2.5,3, 3.5, 4
set.seed(2345)
sim_nguyen <- my_model_nguyen %>% 
  data_set(data) %>%
  Req(CP) %>%
 mrgsim(delta = 1, end = 24)#%>% 
  #filter(time==12)
  #plot()
  #filter(time==23.9)




```


Facchin 

```{r}
code_Facchin <- "

[PROB] #modèle Facchin et al 2009 

[SET] end=100, delta=0.1

[PARAM] @annotated


TVKa: 6.96 : typical Ka (/h)
TVALAG:0.86: typical lag time
TV1: 45 :  typical V1
TV2: 18.5:  typical  V2
TVQ : 1.46 : typical intercompartmental clearance
TVCL:9.07 : clearance typique 
CRCL : -0.768 : effect Creat deviation on CL 
CRBSA: 1.31: effet BSA on cl
VBSA: 1.28: effet BSA on V 
CRSEX:1.15 : effet sexe on cl 
VSEX: 1.14: effet SEX on V 
BSA :1.08  : median BSA
CREA :72.5: median creat 
SEX : 1 : 1 si garçon 0 si fille 


[CMT] @annotated
DEPOT  : Dosing compartment (mg)
CENT : Central compartment
PERI : First peripheral compartment 
 

 [OMEGA] @annotated
ETACL :0.0256 : ETA on clearance
ETAV1 : 0.0086 : ETA on V1
ETAV2 : 0.298 : ETA on V2
ETAKa : 0.350 : ETA on Ka



[MAIN]
 

double Ka = TVKa*exp(ETAKa);
double CL = TVCL*pow(BSA,CRBSA)*pow(CREA/72.5,CRCL)*pow(CRSEX,SEX)*exp(ETACL);
double Q = TVQ ;
double V1 = TV1*pow(BSA,VBSA)*pow(VSEX,SEX)*exp(ETAV1);
double V2 = TV2*exp(ETAV2) ;
ALAG_DEPOT= TVALAG;



[SIGMA] @annotated
ADD: 0.01: additive error log(0.23)

[ODE]
dxdt_DEPOT = -Ka*DEPOT;
dxdt_CENT = Ka*DEPOT -(CL+Q)*CENT/V1 + Q*PERI/V2 ;
dxdt_PERI = Q*CENT/V1 - Q*PERI/V2 ;

[TABLE] 
capture CP = (CENT/V1)+ EPS(1);
int i = 0;
while(CP<0 && i <100) {
simeps();
CP = (CENT/V1)+ EPS(1);
++i;
}

"


my_model_Facchin <- mcode("ganciclovir_model_Facchin", code_Facchin)


my_model_Facchin %>% 
  ev(am = 400 ,ss=1, ii=24) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()

my_model_Facchin %>% 
  ev(am = 600 ,ss=1, ii=24) %>%
  Req(CP) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()


data <- expand.ev(ID = 1:10, amt = 520,ii=24, ss=1)#) #2,2.5,3, 3.5, 4
set.seed(2345)
sim_Facchin <- my_model_Facchin %>% 
  data_set(data) %>%
  Req(CP) %>%
 mrgsim(delta = 1, end = 24)#%>% 
  #filter(time==12)
  #plot()
  #filter(time==23.9)




```

```{r}



e_bene <- expand.ev( ii = 24, ID=1:2700,addl = 5,ss=1) %>%  select(-amt) %>% bind_cols(data_bene)%>% mutate(ID=1:2700)%>%  select(-ID...1,-amt)%>% rename(amt=amt2)


summary(e_bene)

out <- my_model_bene %>% 
  data_set(e_bene) %>%
  Req(CP) %>%
  mrgsim(end = 120, delta = 0.5)

out_bene <- as_tibble(out) %>% left_join(e_bene, by = "ID") %>% filter(CP>0)  

summary(out_bene)

library(PKNCA)


#calcul des AUC 
auc_trap_bene <- out_bene %>% select(time.x,CP,ii,addl,evid,cmt,amt,ID)%>% rename(dose =amt,OUT=CP,TIME=time.x) %>%
filter(between(TIME,24,48))


data.conc <-PKNCAconc(auc_trap_bene,OUT~TIME|ID)


data_obj <- PKNCAdata(data.conc=data.conc,
                      intervals=data.frame(start=24,
                                           end=48,
                                           aucall=F,
                                           auclast=TRUE,
                                           aucinf.pred=F,
                                           aucinf.obs=F))
results_obj <- pk.nca(data_obj)$result


trap1 <- results_obj %>% dplyr::select(ID, trap =PPORRES) %>% mutate(auc = round(trap,5))%>% dplyr::select(-trap)


simu_auc_bene <-left_join(out_bene,trap1) %>% mutate(methode="bene")
summary(simu_auc_bene)





e_pescovitz <- expand.ev( ii = 24, ID=1:2713,addl = 5,ss=1) %>%  select(-amt) %>% bind_cols(data_pescovitz)%>% mutate(ID=1:2713)%>%  select(-ID...1,-amt)%>% rename(amt=amt2)


summary(e_pescovitz)

out_pescovitz <- my_model_pescovitz %>% 
  data_set(e_pescovitz) %>%
  Req(CP) %>%
  mrgsim(end = 120, delta = 0.5)

out_pescovitz <- as_tibble(out_pescovitz) %>% left_join(e_pescovitz, by = "ID") %>% filter(CP>0)  

summary(out_pescovitz)

library(PKNCA)


#calcul des AUC 
auc_trap_pescovitz <- out_pescovitz  %>% select(time.x,CP,ii,addl,evid,cmt,amt,ID)%>% rename(dose =amt,OUT=CP,TIME=time.x) %>%
filter(between(TIME,24,48))


data.conc <-PKNCAconc(auc_trap_pescovitz,OUT~TIME|ID)


data_obj <- PKNCAdata(data.conc=data.conc,
                      intervals=data.frame(start=24,
                                           end=48,
                                           aucall=F,
                                           auclast=TRUE,
                                           aucinf.pred=F,
                                           aucinf.obs=F))
results_obj <- pk.nca(data_obj)$result


trap1 <- results_obj %>% dplyr::select(ID, trap =PPORRES) %>% mutate(auc = round(trap,5))%>% dplyr::select(-trap)


simu_auc_pescovitz <-left_join(out_pescovitz ,trap1)%>% mutate(methode="Pescovitz")
summary(simu_auc_pescovitz )

#### facchin

e_Facchin <- expand.ev( ii = 24, ID=1:2714,addl = 5,ss=1) %>%  select(-amt) %>% bind_cols(data_Facchin)%>% mutate(ID=1:2714)%>%  select(-ID...1,-amt)%>% rename(amt=amt2) %>% mutate(SEX2 = case_when(SEX== "fille"~ "0",SEX== "garcon"~ "1" ))%>% select(-SEX) %>% rename (SEX=SEX2) %>% mutate(BSA=SC_mosteller) %>% mutate (CRE= case_when(age<12~49*taille/Clcreat, age>=12 & SEX <1 ~ 53*taille/Clcreat,age>=12 & SEX>=1 ~ 62*taille/Clcreat ))%>% mutate (CREA = case_when(CRE<350 ~ CRE, CRE>=350 ~ 350))

e_Facchin$SEX=as.numeric(e_Facchin$SEX)
summary(e_Facchin)

out_Facchin <- my_model_Facchin %>% 
  data_set(e_Facchin) %>%
  Req(CP) %>%
  mrgsim(end = 120, delta = 0.5)

out_Facchin <- as_tibble(out_Facchin) %>% left_join(e_Facchin, by = "ID") %>% filter(CP>0)  

summary(out_Facchin)

library(PKNCA)


#calcul des AUC 
auc_trap_Facchin <- out_Facchin  %>% select(time.x,CP,ii,addl,evid,cmt,amt,ID)%>% rename(dose =amt,OUT=CP,TIME=time.x) %>%
filter(between(TIME,24,48))


data.conc <-PKNCAconc(auc_trap_Facchin,OUT~TIME|ID)


data_obj <- PKNCAdata(data.conc=data.conc,
                      intervals=data.frame(start=24,
                                           end=48,
                                           aucall=F,
                                           auclast=TRUE,
                                           aucinf.pred=F,
                                           aucinf.obs=F))
results_obj <- pk.nca(data_obj)$result


trap1 <- results_obj %>% dplyr::select(ID, trap =PPORRES) %>% mutate(auc = round(trap,5))%>% dplyr::select(-trap)


simu_auc_Facchin<-left_join(out_Facchin ,trap1)%>% mutate(methode="Facchin")
summary(simu_auc_Facchin)

####  simulation nguyen

e_nguyen <- expand.ev( ii = 24, ID=1:2673,addl = 5,ss=1) %>%  select(-amt) %>% bind_cols(data_nguyen)%>% mutate(ID=1:2673)%>%  select(-ID...1,-amt)%>% rename(amt=amt2) 


summary(e_nguyen)

out_nguyen <- my_model_nguyen %>% 
  data_set(e_nguyen) %>%
  Req(CP) %>%
  mrgsim(end = 120, delta = 0.5)

out_nguyen <- as_tibble(out_nguyen) %>% left_join(e_nguyen, by = "ID") %>% filter(CP>0)  

summary(out_nguyen)

library(PKNCA)



auc_trap_nguyen<- out_nguyen  %>% select(time.x,CP,ii,addl,evid,cmt,amt,ID)%>% rename(dose =amt,OUT=CP,TIME=time.x) %>%
filter(between(TIME,24,48))


data.conc <-PKNCAconc(auc_trap_nguyen,OUT~TIME|ID)


data_obj <- PKNCAdata(data.conc=data.conc,
                      intervals=data.frame(start=24,
                                           end=48,
                                           aucall=F,
                                           auclast=TRUE,
                                           aucinf.pred=F,
                                           aucinf.obs=F))
results_obj <- pk.nca(data_obj)$result


trap1 <- results_obj %>% dplyr::select(ID, trap =PPORRES) %>% mutate(auc = round(trap,5))%>% dplyr::select(-trap)


simu_auc_nguyen<-left_join(out_nguyen ,trap1)%>% mutate(methode="nguyen")
summary(simu_auc_nguyen)


simu_auc_Facchin$SEX=as.factor(simu_auc_Facchin$SEX)

simu_auc_Facchin<- simu_auc_Facchin%>% mutate(SEX2 = case_when(SEX== "0"~ "fille",SEX== "1"~ "garcon" ))%>% select(-SEX)%>% rename (SEX=SEX2)


simu_auc <- bind_rows(simu_auc_Facchin)%>% bind_rows(simu_auc_pescovitz)%>% bind_rows(simu_auc_nguyen)%>% bind_rows(simu_auc_bene)
summary(simu_auc)
hist(simu_auc$auc)
quantile(simu_auc$auc, c(0.05, 0.5, 0.95))

auc <- simu_auc %>%
        filter(time.x==48)%>%  filter(auc <= 109 & auc>=15 )
 

summary(auc)

auc_final <- auc %>% select(Pds, Clcreat,age,taille,amt,auc,SEX,methode,greffe,Clcreat2)

summary(auc_final)
library(compareGroups)

table1 <- compareGroups(methode ~ Pds+Clcreat+Clcreat2+age+taille+amt+auc+SEX+greffe,data = auc_final, method = 2)
                       
restable1 <- createTable(table1, show.all = T)

restable1
 

```



```{r}
summary(auc_final)



auc_classification <- auc_final %>% select(-Clcreat2) %>% mutate(events=case_when(auc>=40 & auc <=60~ "1", auc >60 ~ "0",auc<40 ~ "0"))
summary(auc_classification)
auc_classification$events=as.factor(auc_classification$events)


auc_ml <- auc_classification %>% select(-auc,-methode) 


```

```{r}
set.seed(1)

auc_ml_split <- initial_split(auc_ml,strata = events)
auc_ml_train <- training(auc_ml_split)
auc_ml_test  <- testing(auc_ml_split)


folds <- rsample::vfold_cv(auc_ml_train, v = 5)

auc_ml_rec <- 
  recipe(events ~ ., data = auc_ml_train) %>%
  step_normalize(all_numeric_predictors())%>%
  step_dummy(greffe,SEX) %>%
  #step_zv(all_predictors()) %>%
  themis::step_upsample(events, over_ratio = 1)
  

auc_ml_wflow <- 
  workflow() %>% 
  add_recipe(auc_ml_rec)



prepped <- prep(auc_ml_rec)
prepped


preproc_data <- juice(prepped)
preproc_data



```

```{r}
library(stacks)
ctrl_grid <- control_stack_grid()



rand_forest_spec <- 
  rand_forest(
    mtry = tune(),
    min_n = tune(),
    trees = 500
  ) %>%
  set_mode("classification") %>%
  set_engine("ranger")

rand_forest_wflow <-
  auc_ml_wflow %>%
  add_model(rand_forest_spec)

rand_forest_res <- 
  tune_grid(
    object = rand_forest_wflow, 
    resamples = folds, 
    grid = 10,
    control = ctrl_grid
  )


nnet_spec <-
  mlp(hidden_units = tune(), penalty = tune(), epochs = tune()) %>%
  set_mode("classification") %>%
  set_engine("nnet")

nnet_rec <- 
  auc_ml_rec %>% 
  step_normalize(all_predictors())

nnet_wflow <- 
  auc_ml_wflow %>%
  add_model(nnet_spec)

nnet_res <-
  tune_grid(
    object = nnet_wflow, 
    resamples = folds, 
    grid = 10,
    control = ctrl_grid
  )


xgb_spec <- boost_tree(mode = "classification",
                       mtry = tune(),
                         trees = 500,
                        min_n = tune(),                        
                        tree_depth = tune(),
                       learn_rate = tune(),
                         sample_size = tune()) %>% set_engine("xgboost")

xgb_wflow <- 
  auc_ml_wflow %>%
  add_model(xgb_spec)

tune_xgb <- tune_grid(
   xgb_wflow,
  resamples = folds,
   grid = 10, 
   control = ctrl_grid
 )





```

```{r}
auc_ml_model_st <- 
  # initialize the stack
  stacks() %>%
  # add candidate members
  add_candidates(rand_forest_res) %>%
  add_candidates(nnet_res) %>%
  add_candidates(tune_xgb)%>%
  # determine how to combine their predictions
  blend_predictions() %>%
  # fit the candidates with nonzero stacking coefficients
  fit_members()


autoplot(auc_ml_model_st)

autoplot(auc_ml_model_st, type = "members")

autoplot(auc_ml_model_st, type = "weights")

auc_ml_pred <-
  auc_ml_train %>%
  bind_cols(predict(auc_ml_model_st, ., type = "prob"))


auc_ml_pred_class_train <-
  auc_ml_train %>%
  bind_cols(predict(auc_ml_model_st, ., type = "class"))


 

   ##confusion matrix
auc_ml_pred_class_train %>%
    conf_mat(events, .pred_class) %>%
    autoplot(type = "heatmap")




conf_mat(auc_ml_pred_class_train, 
         truth = events,
         estimate = .pred_class) %>% 
  summary(event_level = "second")




library(tidymodels)


#. IV

auc_ml_pred <-
  auc_ml_train %>%
  bind_cols(predict(auc_ml_model_st, ., type = "prob"))

auc_ml_pred_class <-
  auc_ml_train %>%
  bind_cols(predict(auc_ml_model_st, ., type = "class"))


 

   ##confusion matrix
auc_ml_pred_class %>%
    conf_mat(events, .pred_class) %>%
    autoplot(type = "heatmap")

stack_PO <- auc_ml_pred_class%>% accuracy(truth = events, estimate = .pred_class)


threshold_df_stack_PO <- auc_ml_pred %>% 
  roc_curve(truth = events,
            .pred_0)
threshold_df_stack_PO


threshold_df_stack_PO %>% 
  autoplot()





auc_ml_pred_class_train <-
  auc_ml_train %>%
  bind_cols(predict(auc_ml_model_st, ., type = "class"))

table(auc_ml_pred_class_train$events,auc_ml_pred_class_train$.pred_class)

conf_mat(auc_ml_pred_class_train, 
         truth = events,
         estimate = .pred_class) %>% 
  summary()

roc_auc(auc_ml_pred,truth=events,pred=.pred_1,event_level = "second")

?



```










prediction 

```{r}

Pds=as.vector(as.matrix(auc_ml[,"Pds"]))
Clcreat=as.vector(as.matrix(auc_ml[,"Clcreat"]))
taille=as.vector(as.matrix(auc_ml[,"taille"]))
SEX=as.vector(as.matrix(auc_ml[,"SEX"]))
greffe=as.vector(as.matrix(auc_ml[,"greffe"]))
age=as.vector(as.matrix(auc_ml[,"age"]))




dose_search = function(Pds,taille,Clcreat,SEX,greffe,age,amt2=case_when(
  Clcreat<150~(sqrt((Pds*taille)/3600)*7*Clcreat),
  Clcreat>=150~(sqrt((Pds*taille)/3600)*1050)))#,amt=seq(0.5*amt2, 2*amt2, by=5))
{
  nombre_ligne=length(Pds)
  res_tibble=tibble(id=numeric(0),Pds=numeric(0),taille=numeric(0), Clcreat=numeric(0),SEX=character(0),greffe=character(0),age=numeric(0),amt=numeric(0))
  for(id in seq(1,nombre_ligne))
{
  Pds_val=Pds[id]
  Taille_val=taille[id]
  Clcreat_val=Clcreat[id]
  SEX_val=SEX[id]
  greffe_val=greffe[id]
  age_val=age[id]
  amt2_val=amt2[id]
  print("amt2_val=")
  print(amt2_val)
  amt_val=seq(0.1*amt2_val, 10*amt2_val, by=5)

  tibble_data = tibble(id=id,Pds=Pds_val, taille=Taille_val, Clcreat=Clcreat_val, SEX=SEX_val,greffe=greffe_val,age=age_val,amt=amt_val,)
  #if(predict(fit_workflow_rf, tibble_data)
   # return(dose_val)
  res_tibble=bind_rows(res_tibble,tibble_data)
  }
  return(res_tibble)
}

res_dosesearch_test <- dose_search(Pds=Pds,Clcreat = Clcreat,taille=taille,SEX=SEX,greffe=greffe,age=age)


library(tidymodels)
### on sevegarde le modèle meilleur 







res_dosesearch_test <- res_dosesearch_test %>% mutate(proba=predict(auc_ml_model_st, res_dosesearch_test,type="prob")[[2]])

res_dosesearch_test2 <-res_dosesearch_test %>% group_by(id) %>% filter(proba == max(proba))#%>% dplyr::slice(n=1)%>% rename(dose_ml=amt)%>% select(proba,dose_ml,id)

res_dosesearch_test2 <-res_dosesearch_test %>% group_by(id) %>% filter(proba == max(proba))%>% rename(dose_ml=amt)%>% select(proba,dose_ml,id)
summary(res_dosesearch_test2)

table_simulation <- res_dosesearch_test2 %>% bind_cols(auc_classification) 


table_simulation <- table_simulation %>%  mutate(dose_ml2= if_else(dose_ml<900,dose_ml,900))







```


